# Generated by Django 3.2.3 on 2021-05-27 14:42

from django.db import migrations, models
import readexcel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=readexcel.models.user_directory_path)),
            ],
        ),
    ]
